version: "3.9"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/backend-devops:latest
    container_name: backend
    ports:
      - "8081:8080"
    environment:
      ConnectionStrings__DefaultConnection: ${DB_CONNECTION}
    restart: always

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend-devops:latest
    container_name: frontend
    ports:
      - "8080:80"
    restart: always