services:
  backend:
    image: ${DOCKERHUB_USERNAME}/backend-devops:latest
    container_name: backend
    ports:
      - "8081:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=dpg-d4jaufchg0os73bm4g40-a.singapore-postgres.render.com;Port=5432;Database=dbdevops_rsbr;Username=dbdevops_rsbr_user;Password=VMBD1FWKYV9UlFxyyuZCd2OCh32zyYRQ"
    restart: always
  
  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend-devops:latest
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      VITE_API_URL: http://18.212.204.247:8081
    restart: always