name: Build & Push Docker Images to Docker Hub via Compose

on:
  push:
    branches: ["master"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Export DockerHub username as env
        run: echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV

      - name: Build images using docker-compose
        run: docker compose build

      - name: Push images
        run: docker compose push
  
  deploy_to_ec2:
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .env file dynamically
        run: |
          echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" > .env
          echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env

      - name: Copy docker-compose + env to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 3.88.87.79
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml,.env"
          target: "/home/ubuntu/app"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 3.88.87.79
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app
            docker compose -f docker-compose-deploy.yml pull
            docker compose -f docker-compose-deploy.yml up --pull always -d
            docker system prune -f